require("katex/dist/katex.min.css")
require("prismjs/themes/prism-tomorrow.css")
require("prismjs/plugins/line-numbers/prism-line-numbers.css")
require("./src/styles/markdown.css")
require("./src/styles/custom.css")
require("./src/styles/style.scss")
